### ISSUE TITLE
Gear Manager stops working

### ISSUE THREAD

**Issue by NakedFaerie** [owenworley/Xposed-Disable_Galaxy_Gear_Notifications#2]
I installed the Gear Manager hider and it says the watch works fine. Not really true. Well yea the watch does work fine but Gear Manager will always say its disconnected and refuse to work.

**Comment by chiggpatel** [comment]
[How to Download and Install Samsung gear manager app](http://www.themobileupdates.com/how-to/how-to-download-and-install-samsung-gear-manager-app-samsung-galaxy-gear-manager-samsung-galaxy-gear-smartwatch/), Samsung galaxy gear manager, Samsung galaxy gear Smartwatch

**Comment by Faslane** [comment]
Thanks but this is old. I have an S2 now. You were replying to a couple year old post. I think.
